### ISSUE TITLE
Info shows enormous amount of grins after sending grin

### ISSUE THREAD

**Issue by LucCADORET** [vault713/wallet713#152] opened 2019-04-19 10:28 UTC
With a balance of 0.092 grins, I was trying to send 0.01 grin on the floonet. Out show grin sent successfully, however using the "info" command then show an enormous amount of grins awaiting for confirmation (18 billions, actually).
![Screenshot from 2019-04-19 12-29-04](https://user-images.githubusercontent.com/6899891/56420562-c02c6300-629e-11e9-86e8-866350ca64e0.png)

**Comment by lehnberg** [comment] 2019-04-19 10:38
What happens if you run `check` command?

**Comment by jaspervdm** [comment] 2019-04-19 20:16
I think this is a duplicate of https://github.com/vault713/wallet713/issues/142. I'm working on fixing it

**Closed** 2019-05-07 13:08 UTC
